# 1. record point cloud

In [1]:
import sys
import os

# Get the current working directory (used to replace __file__)
current_dir = os.getcwd()

target_path1 = os.path.abspath(os.path.join(current_dir, '../3_move'))
target_path2 = os.path.abspath(os.path.join(current_dir, '../1_getPointCloud'))

# Add the paths to sys.path
if target_path1 not in sys.path:
    sys.path.append(target_path1)
    
if target_path2 not in sys.path:
    sys.path.append(target_path2)
# Check if the paths were added successfully
print("Current Python Path:")
print("\n".join(sys.path))

from ImageRecognizer import ImageRecognizer
image_recognizer = ImageRecognizer(top_dir="/opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/2_perception/cubes/")

from utils import matrix_to_rpy_and_translation

from PickAndPlace import PickAndPlace

pick_place = PickAndPlace(approach_distance=0.3, restart=True)

Current Python Path:

/opt/ros_ws/devel/lib/python3/dist-packages
/opt/ros/noetic/lib/python3/dist-packages
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/3_move
/opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/1_getPointCloud


INFO - 2025-03-24 00:32:08,249 - topics - topicmanager initialized


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[INFO] [1742776328.469337, 0.000000]: Waiting for move_group action server...
[ INFO] [1742776328.471598255]: Loading robot model 'panda'...
[ INFO] [1742776329.630174851, 677.928000000]: Ready to take commands for planning group panda_manipulator.


[ WARN] [1742776328.495741714]: Link zed2_holder has visual geometry but no collision geometry. Collision geometry will be left empty. Fix your URDF file by explicitly specifying collision geometry.


[INFO] [1742776329.633447, 0.000000]: Table added to the scene to prevent collision below z = 0.001
[INFO] [1742776329.635815, 0.000000]: Wall 'wall_right' added to the scene with rotation theta=-0.7853981633974483 radians at position: 0.0, 0.8, 0.0
[INFO] [1742776329.638132, 0.000000]: Wall 'wall_left' added to the scene with rotation theta=0.7853981633974483 radians at position: 0.0, -0.8, 0.0
[INFO] [1742776329.639084, 677.937000]: MoveRobot initialized successfully.
[INFO] [1742776329.869338, 678.153000]: Current joint values: [-2.7193123587074997, -0.2065849798509003, 2.123642072486204, -1.9446196233850204, 0.19669424918416034, 2.0408322569820037, -1.4616451166605682]
[INFO] [1742776329.877676, 678.175000]: Waiting for gripper action servers...
[INFO] [1742776330.201103, 678.497000]: Gripper action servers ready.


In [2]:
from save_point_cloud import PointCloudSaver
import open3d as o3d
import rospy
point_cloud_saver = PointCloudSaver()

# Wait for data to be ready
rospy.loginfo("Waiting for data...")
rospy.sleep(1)  # Wait for topic data to be published

# Save the point cloud
world_file = "/opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/2_perception/mesh/zed_point_cloud_world3.ply"
point_cloud_saver.save_point_clouds(world_file)

[INFO] [1742776343.580195, 691.809000]: Waiting for data...
[INFO] [1742776343.649154, 691.881000]: Received image message.
[INFO] [1742776343.675687, 691.883000]: Received point cloud data.


[ WARN] [1742776344.920727576, 693.131000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 693.105000 according to authority unknown_publisher
[ WARN] [1742776344.931178869, 693.142000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 693.105000 according to authority /my_gripper_node_71928_1742776328347
[ WARN] [1742776345.131737939, 693.331000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 693.317000 according to authority unknown_publisher
[ WARN] [1742776345.137503668, 693.337000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 693.317000 according to authority /my_gripper_node_71928_1742776328347
[ WARN] [1742776345.360995534, 693.539000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 693.52600

[INFO] [1742776346.177940, 694.313000]: Color range - Min: [0.10196078 0.10196078 0.10196078], Max: [0.70196078 0.60784314 0.60784314]
[INFO] [1742776346.180008, 694.319000]: Requesting transform from world to left_camera_link_optical...
[INFO] [1742776346.181903, 694.321000]: Transform found: header: 
  seq: 0
  stamp: 
    secs: 694
    nsecs: 300000000
  frame_id: "world"
child_frame_id: "left_camera_link_optical"
transform: 
  translation: 
    x: 0.21074797786961397
    y: -0.059958558303076434
    z: 0.5570633141644737
  rotation: 
    x: 0.6601932466137219
    y: 0.6605923269640532
    z: 0.25267019392296003
    w: 0.25282489550039294
[INFO] [1742776346.459634, 694.598000]: Transformed point cloud saved to /opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/2_perception/mesh/zed_point_cloud_world3.ply


[ WARN] [1742776346.415755984, 694.554000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 694.545000 according to authority unknown_publisher
[ WARN] [1742776346.416452550, 694.555000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 694.545000 according to authority /my_gripper_node_71928_1742776328347


In [3]:
import open3d as o3d
import numpy as np
from utils import filter_point_cloud_by_depth_and_range, filter_point_cloud_by_depth

# zed_ply_path = "mesh/zed_point_cloud_world3.ply"
zed_ply_path = "/opt/ros_ws/src/franka_zed_gazebo/scripts/mycode_clean/2_perception/mesh/zed_point_cloud_world3.ply"

coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=0.1,  # Size of the coordinate axes, can be adjusted as needed
    origin=[0, 0, 0]  # Origin of the coordinate axes
)

# Read the point cloud file
point_cloud = o3d.io.read_point_cloud(zed_ply_path)
if not point_cloud.has_points():
    raise ValueError(f"Failed to read point cloud from {zed_ply_path}")
filtered_point_cloud = filter_point_cloud_by_depth_and_range(point_cloud, depth_threshold=0.02, range=[0.001, -0.8, 1, 1.6])
o3d.visualization.draw_geometries([filtered_point_cloud, coordinate_frame], window_name="Filtered Point Cloud")

[ WARN] [1742776348.411170414, 696.470000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 696.456000 according to authority unknown_publisher
[ WARN] [1742776348.412216438, 696.471000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 696.456000 according to authority /my_gripper_node_71928_1742776328347


In [4]:
# from utils import calculate_max_layer

# # Example usage
# max_layer = calculate_max_layer(filtered_point_cloud, layer_height=0.04)
# print(f"MaxLayer: {max_layer}")

# 2. Perception

## 2.1 Coarse and Fine registration 

In [5]:
import copy
import open3d as o3d
import numpy as np

def register_and_filter(pointcloud, mesh, voxel_size=0.01):
    # Convert mesh to point cloud
    if isinstance(mesh, o3d.geometry.TriangleMesh):
        mesh_pointcloud = mesh.sample_points_uniformly(number_of_points=1000)
    elif isinstance(mesh, o3d.geometry.PointCloud):
        mesh_pointcloud = copy.deepcopy(mesh)
    
    # Downsample the point cloud and compute features
    def preprocess_point_cloud(pcd, voxel_size):
        pcd_down = pcd.voxel_down_sample(voxel_size)
        pcd_down.estimate_normals(
            search_param=o3d.geometry.KDTreeSearchParamHybrid(
                radius=voxel_size*2, 
                max_nn=30
            )
        )
        pcd_fpfh = o3d.pipelines.registration.compute_fpfh_feature(
            pcd_down,
            search_param=o3d.geometry.KDTreeSearchParamHybrid(
                radius=voxel_size*5, 
                max_nn=100
            )
        )
        return pcd_down, pcd_fpfh

    # Coarse registration
    def execute_global_registration(source_down, target_down, source_fpfh, target_fpfh, voxel_size):
        distance_threshold = voxel_size * 1.5
        result = o3d.pipelines.registration.registration_ransac_based_on_feature_matching(
            source_down, target_down, source_fpfh, target_fpfh, True,
            distance_threshold,
            o3d.pipelines.registration.TransformationEstimationPointToPoint(False),
            4,
            [
                o3d.pipelines.registration.CorrespondenceCheckerBasedOnEdgeLength(0.9),
                o3d.pipelines.registration.CorrespondenceCheckerBasedOnDistance(distance_threshold)
            ],
            o3d.pipelines.registration.RANSACConvergenceCriteria(4000000, 500)
        )
        return result

    # Fine registration
    def refine_registration(source, target, initial_transformation, voxel_size):
        distance_threshold = voxel_size * 1  # Reduce the threshold for higher accuracy
        result = o3d.pipelines.registration.registration_icp(
            source, target, distance_threshold, initial_transformation,
            o3d.pipelines.registration.TransformationEstimationPointToPoint(),
            o3d.pipelines.registration.ICPConvergenceCriteria(max_iteration=1000000)
        )
        return result

    # Execute point cloud preprocessing
    source_down, source_fpfh = preprocess_point_cloud(mesh_pointcloud, voxel_size)
    target_down, target_fpfh = preprocess_point_cloud(pointcloud, voxel_size)

    # Execute registration
    coarse_result = execute_global_registration(source_down, target_down, source_fpfh, target_fpfh, voxel_size)
    refined_result = refine_registration(mesh_pointcloud, pointcloud, coarse_result.transformation, voxel_size)

    # Transform the mesh point cloud
    transform = refined_result.transformation
    transformed_mesh_pointcloud = mesh_pointcloud.transform(transform)

    # Create bounding box
    oriented_bounding_box = transformed_mesh_pointcloud.get_oriented_bounding_box()
    center = oriented_bounding_box.center
    extent = oriented_bounding_box.extent
    rotation_matrix = oriented_bounding_box.R

    # Expand the bounding box
    margin = voxel_size
    expanded_extent = extent + 0.5 * margin
    expanded_bounding_box = o3d.geometry.OrientedBoundingBox(
        center=center,
        extent=expanded_extent,
        R=rotation_matrix
    )

    # Filter the point cloud
    indices_inside_box = expanded_bounding_box.get_point_indices_within_bounding_box(pointcloud.points)
    indices_outside_box = list(set(range(len(pointcloud.points))) - set(indices_inside_box))

    # Separate the point cloud
    remaining_pointcloud = pointcloud.select_by_index(indices_outside_box)
    deleted_pointcloud = pointcloud.select_by_index(indices_inside_box)

    return transform, remaining_pointcloud, deleted_pointcloud, refined_result.fitness


In [6]:
# Read the cube
# Define file paths
cube_obj_path = "mesh/cube_0.obj"
zed_ply_path = "mesh/zed_point_cloud_world3.ply"

# Read the cube_0.obj mesh
cube_mesh = o3d.io.read_triangle_mesh(cube_obj_path)
cube_mesh.compute_vertex_normals()  # Compute normals for better visualization
# cube_point_cloud = cube_mesh.sample_points_uniformly(number_of_points=50000)  # Convert to point cloud
# cube_point_cloud = cube_mesh.sample_points_poisson_disk(number_of_points=1000)

# Remove the lower part of the cube to prevent flipping along the z-axis
# cube_point_cloud = filter_point_cloud_by_depth(cube_point_cloud, depth_threshold=-0.015)
# o3d.visualization.draw_geometries([cube_point_cloud])


coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
    size=0.1,  # Size of the coordinate axes, can be adjusted as needed
    origin=[0, 0, 0]  # Origin of the coordinate axes
)


In [7]:
def check_transform_z_axis_alignment(transform, tolerance=0.1):
    """
    Check if the Z-axis of the transform is parallel to the Z-axis of the world coordinate system.
    Allows a certain tolerance range to check if it is parallel or anti-parallel.
    
    Args:
    - transform: 4x4 transformation matrix
    - tolerance: Tolerance range for checking, default is 0.1
    
    Returns:
    - True: If the Z-axis is parallel or anti-parallel
    - False: If the Z-axis is not parallel
    - The corrected transform
    """
    z_axis = np.array([0, 0, 1])  # Z-axis of the world coordinate system
    transform_z_axis = transform[:3, 2]  # Get the Z-axis of the transform (i.e., the third column of the rotation matrix)

    # Compute the angle between the transform's Z-axis and the world coordinate system's Z-axis
    dot_product = np.dot(transform_z_axis, z_axis)
    # Compute the cosine of the angle, if close to 1 or -1, it means parallel or anti-parallel
    if np.abs(dot_product) > (1 - tolerance):
        return True
    return False

def align_transform_z_axis(transform):
    """
    If the Z-axis of the transform is anti-parallel to the Z-axis of the world coordinate system,
    rotate by 180 degrees around the X-axis (np.pi) to flip the direction of the Z-axis.
    
    Args:
    - transform: 4x4 transformation matrix
    
    Returns:
    - The corrected transform matrix
    """
    z_axis_world = np.array([0, 0, 1])  # Z-axis of the world coordinate system
    transform_z_axis = transform[:3, 2]  # Get the Z-axis of the transform (the third column of the rotation matrix)

    # Check if the Z-axis is anti-parallel to the world coordinate system's Z-axis
    if np.dot(transform_z_axis, z_axis_world) < 0:  # Z-axis is anti-parallel
        print("Correcting Z axis")
        # Create a rotation matrix to rotate 180 degrees around the X-axis
        rotation_matrix = np.eye(4)
        rotation_matrix[1, 1] = -1  # Rotate the matrix by 180 degrees around the X-axis
        rotation_matrix[2, 2] = -1  # Rotate the matrix by 180 degrees around the X-axis
        
        # Perform matrix multiplication, applying the rotation matrix to the original transform
        transform = np.dot(rotation_matrix, transform)

    return transform

def align_transform_z_axis_any_orientation(transform):
    """
    Aligns the Z-axis of the transform with the negative Z-axis of the world coordinate system,
    no matter what the original orientation is.
    
    Args:
    - transform: 4x4 transformation matrix
    
    Returns:
    - The corrected transform matrix with Z-axis pointing downward
    """
    # Extract the original rotation matrix and translation vector
    rotation = transform[:3, :3]
    translation = transform[:3, 3]
    
    # Extract the current z-axis direction (third column of rotation matrix)
    current_z = rotation[:, 2]
    
    # Target z-axis direction (downward in world coordinates)
    target_z = np.array([0, 0, -1])
    
    # Check if already aligned within a small tolerance
    if np.allclose(current_z, target_z, atol=1e-6):
        return transform
    
    # For completely anti-aligned case (pointing directly up), simple 180° rotation works
    if np.allclose(current_z, -target_z, atol=1e-6):
        # Rotate 180 degrees around x-axis
        r = np.eye(3)
        r[1, 1] = -1
        r[2, 2] = -1
        new_rotation = rotation @ r
    else:
        # For any other orientation, we need to find the rotation that aligns vectors
        # Compute the rotation axis (cross product of current and target z-axes)
        rotation_axis = np.cross(current_z, target_z)
        
        # If current_z and target_z are parallel or anti-parallel, rotation_axis might be zero
        # In that case, choose any perpendicular axis
        if np.allclose(rotation_axis, 0, atol=1e-10):
            # Find a non-zero component in current_z
            if abs(current_z[0]) > 1e-10:
                rotation_axis = np.array([current_z[1], -current_z[0], 0])
            else:
                rotation_axis = np.array([0, current_z[2], -current_z[1]])
        
        # Normalize the rotation axis
        rotation_axis = rotation_axis / np.linalg.norm(rotation_axis)
        
        # Compute the rotation angle (dot product gives cosine of angle)
        # We want the shorter arc between the vectors
        cos_angle = np.dot(current_z, target_z)
        angle = np.arccos(np.clip(cos_angle, -1.0, 1.0))
        
        # Rodrigues' rotation formula to get rotation matrix
        K = np.array([
            [0, -rotation_axis[2], rotation_axis[1]],
            [rotation_axis[2], 0, -rotation_axis[0]],
            [-rotation_axis[1], rotation_axis[0], 0]
        ])
        R = np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)
        
        # Apply the rotation to the original rotation matrix
        new_rotation = rotation @ R
    
    # Create the new transformation matrix
    new_transform = np.eye(4)
    new_transform[:3, :3] = new_rotation
    new_transform[:3, 3] = translation
    
    # Validate the result
    result_z = new_transform[:3, :3][:, 2]
    alignment_quality = np.dot(result_z, target_z)
    print(f"Z-axis alignment quality: {alignment_quality:.6f} (closer to 1 is better)")
    
    return new_transform

def align_transform_z_axis_preserving_xy(transform):
    """
    Align the Z-axis of the transformation matrix to point downward (world -Z axis),
    while preserving the original XY plane orientation as much as possible.

    This function ensures:
    1. The Z-axis points downward (aligned with the world -Z axis)
    2. The XY plane is preserved as much as possible to minimize disruption to the original grasp direction

    Args:
        transform: A 4x4 transformation matrix

    Returns:
        A corrected transformation matrix with the Z-axis pointing downward and XY directions as close as possible to the original
    """
    # Extract the original rotation matrix and translation vector
    rotation = transform[:3, :3]
    translation = transform[:3, 3]

    # Extract current axes directions from the rotation matrix
    x_axis = rotation[:, 0]  # X-axis is the first column
    y_axis = rotation[:, 1]  # Y-axis is the second column
    z_axis = rotation[:, 2]  # Z-axis is the third column

    # Target direction for Z-axis (world -Z direction)
    target_z = np.array([0, 0, -1])

    # Check if the current Z-axis is already aligned with the target
    aligned = np.isclose(np.abs(np.dot(z_axis, target_z)), 1.0, atol=1e-6)
    if aligned and np.dot(z_axis, target_z) > 0:
        # Already aligned, no changes needed
        return transform

    # Set new Z-axis to point down
    new_z = target_z

    # Compute a new X-axis that is orthogonal to the new Z-axis
    # Do this by projecting the original X-axis onto the plane perpendicular to new Z

    new_x = x_axis - np.dot(x_axis, new_z) * new_z

    # If the projection is too small (i.e., X was almost aligned with Z), try using original Y
    if np.linalg.norm(new_x) < 1e-6:
        new_x = y_axis - np.dot(y_axis, new_z) * new_z

    # If still too small, pick an arbitrary vector that's not parallel to Z
    if np.linalg.norm(new_x) < 1e-6:
        temp = np.array([1, 0, 0]) if abs(new_z[0]) < 0.9 else np.array([0, 1, 0])
        new_x = temp - np.dot(temp, new_z) * new_z

    # Normalize the new X-axis
    new_x = new_x / np.linalg.norm(new_x)

    # Calculate the new Y-axis using the cross product (ensures orthogonality)
    new_y = np.cross(new_z, new_x)

    # Construct the new rotation matrix from the orthonormal axes
    new_rotation = np.column_stack((new_x, new_y, new_z))

    # Assemble the final transformation matrix
    new_transform = np.eye(4)
    new_transform[:3, :3] = new_rotation
    new_transform[:3, 3] = translation

    # Evaluate alignment quality of the new Z-axis
    result_z = new_transform[:3, :3][:, 2]
    alignment_quality = np.dot(result_z, target_z)
    print(f"Z-axis alignment quality: {alignment_quality:.6f} (closer to 1 is better)")

    # Evaluate how well the XY plane orientation is preserved
    original_xy_normal = np.cross(x_axis, y_axis)
    original_xy_normal = original_xy_normal / np.linalg.norm(original_xy_normal)

    new_xy_normal = np.cross(new_x, new_y)
    new_xy_normal = new_xy_normal / np.linalg.norm(new_xy_normal)

    xy_preservation = np.abs(np.dot(original_xy_normal, new_xy_normal))
    print(f"XY plane preservation quality: {xy_preservation:.6f} (closer to 1 is better)")

    return new_transform


In [8]:
import rospy
import tf
import numpy as np
from geometry_msgs.msg import TransformStamped

class TransformBroadcaster:
    def __init__(self):
        # Try to initialize the ROS node, avoid initializing multiple times
        try:
            rospy.init_node('tf_broadcaster_node')
        except rospy.exceptions.ROSException:
            pass  # If the node is already initialized, do nothing

        # Create a TransformBroadcaster instance
        self.br = tf.TransformBroadcaster()

        # Assume T is the given 4x4 transformation matrix
        self.T = np.ones((4, 4))  # Set to a 4x4 matrix

        # Set a timer to call the broadcast_transform function every 100 milliseconds
        self.timer = rospy.Timer(rospy.Duration(0.1), self.broadcast_transform)

        # Store the timestamp of the last sent transformation
        self.last_sent_time = None

    def broadcast_transform(self, event):
        try:
            # Extract the translation and rotation parts from the 4x4 matrix
            translation = self.T[0:3, 3]  # Translation part (x, y, z)
            rotation_matrix = self.T[0:3, 0:3]  # Rotation matrix part

            # Create a complete 4x4 matrix, including rotation and homogeneous coordinates
            full_matrix = np.eye(4)
            full_matrix[0:3, 0:3] = rotation_matrix
            full_matrix[0:3, 3] = translation

            # Create a quaternion to represent the rotation
            quaternion = tf.transformations.quaternion_from_matrix(full_matrix)

            # Get the current timestamp
            current_time = rospy.Time.now()

            # Check if the last sent timestamp and the current timestamp are the same
            if self.last_sent_time is None or current_time != self.last_sent_time:
                # Publish the transformation
                self.br.sendTransform(
                    (translation[0], translation[1], translation[2]),  # Translation part
                    (quaternion[0], quaternion[1], quaternion[2], quaternion[3]),  # Rotation part (quaternion)
                    current_time,  # Use the current timestamp
                    "cube",  # Child frame name
                    "world"   # Parent frame name
                )
                # Update the last sent timestamp
                self.last_sent_time = current_time
        except:
            pass

    def update(self, T):
        self.T = T
        
    def stop(self):
        # Stop the timer
        self.timer.shutdown()


## 2.2 Grasp Generation

In [9]:
from utils import *  # Assuming the create_grasp_mesh function is in utils.py
import numpy as np
import open3d as o3d

def generate_gripper_from_transform(T: np.ndarray):
    """
    Generates a robotic gripper mesh from a given 4x4 transformation matrix,
    with additional rotations around x and y axes.

    Args:
        T: 4x4 transformation matrix (numpy array).
        
    Returns:
        gripper_meshes: List of meshes representing the gripper.
    """
    # Extract the rotation matrix (3x3)
    rotation_matrix = T[:3, :3]

    # Extract the translation vector
    translation = T[:3, 3]

    # Set the gripper's center point position, usually the translation vector
    center_point = translation

    # Create a rotation matrix for -90 degrees around the x-axis
    R_x = np.array([
        [1, 0, 0],
        [0, np.cos(-np.pi/2), -np.sin(-np.pi/2)],
        [0, np.sin(-np.pi/2), np.cos(-np.pi/2)]
    ])

    # Create a rotation matrix for 90 degrees around the y-axis
    R_y = np.array([
        [np.cos(np.pi/2), 0, np.sin(np.pi/2)],
        [0, 1, 0],
        [-np.sin(np.pi/2), 0, np.cos(np.pi/2)]
    ])
    
    R_z = np.array([
        [0, -1, 0],
        [1, 0, 0],
        [0, 0, 1]
    ])
    # Combine rotation matrices, first rotate around the x-axis, then around the y-axis
    combined_rotation = R_z @ rotation_matrix @ R_x 

    # Call create_grasp_mesh function to generate the gripper
    gripper_meshes = create_grasp_mesh(
        center_point=center_point, 
        rotation_matrix=combined_rotation,
        width=0.25
    )
    # Call create_grasp_mesh function to generate the gripper with a different rotation
    gripper_meshes_rotate = create_grasp_mesh(
        center_point=center_point, 
        rotation_matrix=rotation_matrix @ R_x,
        width=0.25
    )

    return gripper_meshes, gripper_meshes_rotate


In [10]:
# Test code: Pass in a 4x4 transformation matrix
T = np.array([
    [1, 0, 0, 0.1],  # Rotation matrix and translation
    [0, 1, 0, 0.2],
    [0, 0, 1, 0.3],
    [0, 0, 0, 1]
])

# Call the function to generate the gripper
gripper_meshes, _ = generate_gripper_from_transform(T)

# Visualize the generated gripper
# o3d.visualization.draw_geometries(gripper_meshes)


In [11]:
def check_grasp_collision(
    grasp_meshes: Sequence[o3d.geometry.TriangleMesh],
    object_pcd: o3d.geometry.TriangleMesh,
    num_colisions: int = 10,
    tolerance: float = 0.00001
) -> bool:
    """
    Checks for collisions between a gripper grasp pose and target object
    using point cloud sampling.

    Args:
        grasp_meshes: List of mesh geometries representing the gripper components
        object_mesh: Triangle mesh of the target object
        num_collisions: Threshold on how many points to check
        tolerance: Distance threshold for considering a collision (in meters)

    Returns:
        bool: True if collision detected between gripper and object, False otherwise
    """
    # Combine gripper meshes
    combined_gripper = o3d.geometry.TriangleMesh()
    for mesh in grasp_meshes:
        combined_gripper += mesh  # Combine multiple gripper meshes

    # Sample points from both meshes
    num_points = 5000  # Sample 5000 points from both gripper and target object
    #######################TODO#######################
    # Uniformly sample point clouds from both the gripper and object meshes
    gripper_pcd = combined_gripper.sample_points_uniformly(number_of_points=num_points)
    gripper_points = np.asarray(gripper_pcd.points)  # Point coordinates of the gripper point cloud
    object_points = np.asarray(object_pcd.points)  # Point coordinates of the target object point cloud
    ##################################################
    
    # Build KDTree for object points
    is_collision = False
    #######################TODO#######################
    collision_count = 0
    # Build a KDTree for the target object point cloud
    object_kdtree = o3d.geometry.KDTreeFlann(object_pcd)
    for gripper_point in gripper_points:
        # For each gripper point, find the nearest point in the target object point cloud
        _, _, distances = object_kdtree.search_knn_vector_3d(gripper_point, 1)  # Find the nearest neighbor
        
        # If the distance to the nearest neighbor is less than the tolerance, consider it a collision
        if distances[0] <= tolerance:
            collision_count += 1
            
            # Exit early if enough collisions are detected
            if collision_count >= num_colisions:
                is_collision = True
                break
    #######################TODO#######################

    return is_collision


## 2.3 identify image of cubes

In [12]:
# from openai import OpenAI
# from io import BytesIO
# from PIL import Image
# import base64
# import json
# SYSTEM_PROMPT = """Please act as an image recognition agent. 
# You will be given a square face of a block, 
# which is projected from a point cloud. 
# Your task is to recognize the following:

# Determine if this is a block face.
# Each face contains only one letter, 
# one pattern (just detect whether it's a pattern, no need to identify the exact pattern), 
# or is blank (only wood texture). 
# Please detect whether it is a letter, 
# a pattern, or blank. 
# Each of these may be rotated. 
# Please analyze all possible rotations in a clockwise direction: 0°, 90°, 180°, and 270°.
# There might be a circular border around the face. 
# Please detect if this border exists. 
# It's confirmed that the color of the border matches the color of the letter or pattern.
# The expected output is a JSON in the following format:
# {
#     "check": true/false, 
#     "c": char/"pattern"/"blank", 
#     "color": "green"/"yellow"/"red"/"blue"/"None", 
#     "rotation": 0/90/180/270, 
#     "circle": true/false
# }
# """

# api_key=""
# client = OpenAI(api_key=api_key)

# def encode_image(image, quality=100):
#     if image.mode != 'RGB':
#         image = image.convert('RGB')  # Convert to RGB
#     buffered = BytesIO()
#     image.save(buffered, format="JPEG", quality=quality) 
#     return base64.b64encode(buffered.getvalue()).decode("utf-8")

# def gpt4o_analysis(image_path, quality=50):
#     with Image.open(image_path) as img:
#         img_b64_str = encode_image(img, quality=quality)
#     img_type = "image/jpeg"
#     response = client.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[
#             {
#                 "role": "user",
#                 "content": [
#                     {"type": "text", "text": SYSTEM_PROMPT},
#                     {
#                         "type": "image_url",
#                         "image_url": {"url": f"data:{img_type};base64,{img_b64_str}"},
#                     },
#                 ],
#             }from openai import OpenAI
# from io import BytesIO
# from PIL import Image
# import base64
# import json
# SYSTEM_PROMPT = """Please act as an image recognition agent. 
# You will be given a square face of a block, 
# which is projected from a point cloud. 
# Your task is to recognize the following:

# Determine if this is a block face.
# Each face contains only one letter, 
# one pattern (just detect whether it's a pattern, no need to identify the exact pattern), 
# or is blank (only wood texture). 
# Please detect whether it is a letter, 
# a pattern, or blank. 
# Each of these may be rotated. 
# Please analyze all possible rotations in a clockwise direction: 0°, 90°, 180°, and 270°.
# There might be a circular border around the face. 
# Please detect if this border exists. 
# It's confirmed that the color of the border matches the color of the letter or pattern.
# The expected output is a JSON in the following format:
# {
#     "check": true/false, 
#     "c": char/"pattern"/"blank", 
#     "color": "green"/"yellow"/"red"/"blue"/"None", 
#     "rotation": 0/90/180/270, 
#     "circle": true/false
# }
# """

# api_key=""
# client = OpenAI(api_key=api_key)

# def encode_image(image, quality=100):
#     if image.mode != 'RGB':
#         image = image.convert('RGB')  # Convert to RGB
#     buffered = BytesIO()
#     image.save(buffered, format="JPEG", quality=quality) 
#     return base64.b64encode(buffered.getvalue()).decode("utf-8")

# def gpt4o_analysis(image_path, quality=50):
#     with Image.open(image_path) as img:
#         img_b64_str = encode_image(img, quality=quality)
#     img_type = "image/jpeg"
#     response = client.chat.completions.create(
#         model="gpt-4o-mini",
#         messages=[
#             {
#                 "role": "user",
#                 "content": [
#                     {"type": "text", "text": SYSTEM_PROMPT},
#                     {
#                         "type": "image_url",
#                         "image_url": {"url": f"data:{img_type};base64,{img_b64_str}"},
#                     },
#                 ],
#             }
#         ],
#     )
#     return response.choices[0].message.content
#         ],
#     )
#     return response.choices[0].message.content

In [13]:
import logging
logging.basicConfig(level=logging.ERROR)
import matplotlib.pyplot as plt
import cv2
from PointCloud2Image import enlarge_points_as_cubes, max_downsample_image, pointcloud_to_top_view_image_color, interpolate_sparse_image, pointcloud_to_colored_image_with_filling, triangle_mesh_to_image

try:
    broadcaster
except NameError:
    broadcaster = TransformBroadcaster()           
    
cube_num = 26
def pointcloud_process(point_cloud, slice_tolerance=0.005):
    '''
        Identify the cubes
        Returns:
            [
                json,
                T
            ]
    '''
    orignal_point_cloud = copy.deepcopy(point_cloud)
    T = []
    remaining_pointcloud_count = 10000
    countdown = 50
    # Use open3d to visualize the point cloud
    # o3d.visualization.draw_geometries([layer_point_cloud], window_name=f"Layer {layer} (Z range: {z_min:.4f} to {z_max:.4f})")
    movecount = 0
    while remaining_pointcloud_count > 50 and countdown > 0:
        cube_point_cloud = cube_mesh.sample_points_uniformly(number_of_points=50000) 
        cube_point_cloud = filter_point_cloud_by_depth(cube_point_cloud, depth_threshold=-0.01)
        transform, remaining_pointcloud, deleted_pointcloud, fitness = register_and_filter(point_cloud, cube_point_cloud)
        remaining_pointcloud_count = len(remaining_pointcloud.points)
        # return transform, remaining_pointcloud, deleted_pointcloud
        if fitness > 0.01:
            countdown = countdown - 1
        print(fitness)
        if check_transform_z_axis_alignment(transform) and fitness > 0.50 and np.array_equal(transform, align_transform_z_axis(transform)):
        # if fitness > 0.70:
            if movecount >= cube_num:
                break
            print(movecount)
            

            broadcaster.update(transform)
            cube_coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
                size=0.1,  # Coordinate axis size, can be adjusted as needed
                origin=[0, 0, 0]  # Origin of the coordinate axis
            )
            theta = np.radians(45)  # Convert angle to radians
            transform_matrix_x_180 = np.array([
                [1, 0, 0, 0],
                [0, -1, 0, 0],
                [0, 0, -1, 0],
                [0, 0, 0, 1]
            ])
            transform_matrix_z_90 = np.array([
                [0, -1, 0, 0],
                [1, 0, 0, 0],
                [0, 0, 1, 0],
                [0, 0, 0, 1]
            ])
            graps_transform = transform @ transform_matrix_x_180
            graps_transform_rotate = transform @ transform_matrix_x_180 @ transform_matrix_z_90
                        # o3d.visualization.draw_geometries([coordinate_frame, remaining_pointcloud], window_name="remaining_pointcloud")
            cube_point_cloud_transormed = copy.deepcopy(deleted_pointcloud)
            cube_point_cloud_transormed = cube_point_cloud_transormed.transform(np.linalg.inv(graps_transform))
            cube_point_cloud_transormed_cubes = enlarge_points_as_cubes(cube_point_cloud_transormed)

            cube_top_image = triangle_mesh_to_image(cube_point_cloud_transormed_cubes, image_size=(100, 100))
            cube_top_image = (cube_top_image / cube_top_image.max() * 255).astype(np.uint8)
            grasp_coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
                size=0.1,  # Coordinate axis size, can be adjusted as needed
                origin=[0, 0, 0]  # Origin of the coordinate axis
            )
            grasp_mesh, gripper_meshes_rotate = generate_gripper_from_transform(graps_transform)
            # Apply transformation matrix to the coordinate frame
            grasp_coordinate_frame.transform(graps_transform)
            grasp_final_matrix = None
            # o3d.visualization.draw_geometries(grasp_mesh+gripper_meshes_rotate+[orignal_point_cloud, coordinate_frame], window_name="remaining_pointcloud")
            if check_grasp_collision(grasp_mesh, orignal_point_cloud):
            # if check_grasp_collision(grasp_mesh, deleted_pointcloud):
                # If collision
                grasp_mesh = []
            else:
                grasp_final_matrix = graps_transform
            if check_grasp_collision(gripper_meshes_rotate, orignal_point_cloud):
            # if check_grasp_collision(gripper_meshes_rotate, deleted_pointcloud):
                gripper_meshes_rotate = []
            else:
                grasp_final_matrix = graps_transform_rotate
            # o3d.visualization.draw_geometries(grasp_mesh+gripper_meshes_rotate+[grasp_coordinate_frame, deleted_pointcloud, coordinate_frame], window_name="deleted_pointcloud")
            # o3d.visualization.draw_geometries(grasp_mesh+gripper_meshes_rotate+[grasp_coordinate_frame, remaining_pointcloud, coordinate_frame], window_name="deleted_pointcloud")
            if grasp_final_matrix is not None: # Can move
                countdown = 50
                print(grasp_final_matrix)
                movecount += 1
                pick_rpy, pick_pos = matrix_to_rpy_and_translation(grasp_final_matrix)
                pick_pos_ = [a + b for a, b in zip(pick_pos, [0, 0, 0.10])]
                pick_rpy = [a + b for a, b in zip(pick_rpy, [0, 0, 0])]
                # pick_place.move(pick_pos_, pick_rpy)
                print(pick_pos_, pick_rpy)
                # cube_top_image = point_cloud_to_image(cube_point_cloud_transormed)
                plt.imsave(f"test_{movecount}.png", cube_top_image)
                plt.show()
                point_cloud = remaining_pointcloud
                # TODO: Identify the first face
            
                T.append(grasp_final_matrix)
        else:
            cube_point_cloud = cube_mesh.sample_points_uniformly(number_of_points=50000)
            cube_point_cloud = filter_point_cloud_by_depth(cube_point_cloud, depth_threshold=-0.01)
    print(T)
    return T

# def pointcloud_process(point_cloud, slice_tolerance=0.005, cube_num=cube_num):
#     '''
#     Identify the cubes in a point cloud and determine their transformation matrices for grasping.
#     Handles alignment of Z-axis in any orientation for proper grasping.
    
#     Args:
#         point_cloud: The input point cloud containing cubes to be identified
#         slice_tolerance: Tolerance for slicing the point cloud
#         cube_num: Maximum number of cubes to detect
        
#     Returns:
#         A list of transformation matrices for grasping the identified cubes
#     '''
#     original_point_cloud = copy.deepcopy(point_cloud)
#     T = []
#     remaining_pointcloud = point_cloud
#     remaining_pointcloud_count = len(point_cloud.points)
#     countdown = 50
#     movecount = 0
    
#     # Define standard transformation matrices for grasping
#     transform_matrix_x_180 = np.array([
#         [1, 0, 0, 0],
#         [0, -1, 0, 0],
#         [0, 0, -1, 0],
#         [0, 0, 0, 1]
#     ])
    
#     transform_matrix_z_90 = np.array([
#         [0, -1, 0, 0],
#         [1, 0, 0, 0],
#         [0, 0, 1, 0],
#         [0, 0, 0, 1]
#     ])
    
#     # Function to check if a cube's z-axis points approximately downward
#     def is_z_axis_pointing_down(transform):
#         z_axis = transform[:3, 2]  # Extract z-axis vector
#         return np.dot(z_axis, np.array([0, 0, -1])) > 0.8  # Check if close to pointing down
    
#     while remaining_pointcloud_count > 50 and countdown > 0 and movecount < cube_num:
#         # Sample points from the cube mesh model
#         cube_point_cloud = cube_mesh.sample_points_uniformly(number_of_points=50000) 
#         cube_point_cloud = filter_point_cloud_by_depth(cube_point_cloud, depth_threshold=-0.01)
        
#         # Register the cube in the point cloud
#         transform, remaining_pointcloud, deleted_pointcloud, fitness = register_and_filter(
#             remaining_pointcloud, cube_point_cloud
#         )
        
#         remaining_pointcloud_count = len(remaining_pointcloud.points)
        
#         # Decrement countdown if the fitness is above a minimum threshold
#         if fitness > 0.01:
#             countdown -= 1
            
#         print(f"Iteration {50-countdown}: Fitness = {fitness:.4f}, Remaining points: {remaining_pointcloud_count}")
        
#         # Check if the fitness is above the acceptable threshold
#         if fitness > 0.40:  # Lowered threshold slightly for more detections
#             print(f"Processing cube #{movecount+1}")
            
#             # Align the Z-axis to point downward regardless of original orientation
#             aligned_transform = align_transform_z_axis_any_orientation(transform)
            
#             # Update the transform broadcaster for visualization
#             if 'broadcaster' in globals():
#                 broadcaster.update(aligned_transform)
            
#             # Create grasp transforms
#             grasp_transform = aligned_transform @ transform_matrix_x_180
#             grasp_transform_rotate = aligned_transform @ transform_matrix_x_180 @ transform_matrix_z_90
            
#             # Transform the detected cube point cloud for visualization
#             cube_point_cloud_transformed = copy.deepcopy(deleted_pointcloud)
#             cube_point_cloud_transformed = cube_point_cloud_transformed.transform(np.linalg.inv(grasp_transform))
            
#             # For generating a visual representation as a top-down view
#             try:
#                 cube_point_cloud_transformed_cubes = enlarge_points_as_cubes(cube_point_cloud_transformed)
#                 cube_top_image = triangle_mesh_to_image(cube_point_cloud_transformed_cubes, image_size=(100, 100))
#                 cube_top_image = (cube_top_image / cube_top_image.max() * 255).astype(np.uint8)
#                 plt.imsave(f"cube_{movecount+1}_top_view.png", cube_top_image)
#             except Exception as e:
#                 print(f"Warning: Could not generate top view image: {e}")
            
#             # Generate gripper meshes for collision checking
#             grasp_mesh, gripper_meshes_rotate = generate_gripper_from_transform(grasp_transform)
            
#             # Find a valid grasp without collisions
#             grasp_final_matrix = None
            
#             # Check first grasping orientation
#             if not check_grasp_collision(grasp_mesh, original_point_cloud):
#                 grasp_final_matrix = grasp_transform
#                 print("Using standard grasp orientation")
#             # Check alternative grasping orientation (rotated by 90° around Z)
#             elif not check_grasp_collision(gripper_meshes_rotate, original_point_cloud):
#                 grasp_final_matrix = grasp_transform_rotate
#                 print("Using 90° rotated grasp orientation")
#             else:
#                 print("Both grasp orientations have collisions, skipping this cube")
                
#             # If a valid grasp pose was found
#             if grasp_final_matrix is not None:
#                 # Reset countdown
#                 countdown = 50
                
#                 # Calculate RPY and position for robot movement
#                 pick_rpy, pick_pos = matrix_to_rpy_and_translation(grasp_final_matrix)
#                 approach_offset = [0, 0, 0.10]  # 10cm above the cube for approach
#                 pick_pos_approach = [a + b for a, b in zip(pick_pos, approach_offset)]
                
#                 print(f"Cube #{movecount+1} grasp position: {pick_pos}")
#                 print(f"Approach position: {pick_pos_approach}")
#                 print(f"RPY orientation: {pick_rpy}")
                
#                 # Add the transform to our results
#                 T.append(grasp_final_matrix)
#                 movecount += 1
                
#                 # Optional visualization of the detected cube
#                 # o3d.visualization.draw_geometries([deleted_pointcloud], window_name=f"Detected Cube #{movecount}")
                
#                 # Optional visualization of the grasp
#                 # vis_geometries = grasp_mesh + [create_coordinate_frame(0.1)]
#                 # o3d.visualization.draw_geometries(vis_geometries, window_name=f"Grasp Visualization #{movecount}")
#         else:
#             # If fitness is too low, don't change the countdown
#             pass
    
#     print(f"Found {len(T)} cubes from {50-countdown} iterations")
    
#     # Print the final transforms
#     for i, transform in enumerate(T):
#         print(f"Cube #{i+1} Transform:")
#         print(transform)
        
#     return T
def pointcloud_process_2(point_cloud, slice_tolerance=0.005, cube_num=4):
    '''
    在点云中识别立方体并确定抓取的变换矩阵。
    使用改进的Z轴对齐方法，保持XY平面的一致性，以减少对齐误差。
    
    参数：
        point_cloud: 输入的点云，包含要检测的立方体
        slice_tolerance: 用于切割点云的容差值
        cube_num: 最大检测的立方体数量
        
    返回：
        与检测到的可抓取立方体对应的变换矩阵列表
    '''
    original_point_cloud = copy.deepcopy(point_cloud)
    T = []
    remaining_pointcloud = point_cloud
    remaining_pointcloud_count = len(point_cloud.points)
    countdown = 50
    movecount = 0

    # 定义用于抓取方向的标准变换矩阵
    transform_matrix_x_180 = np.array([
        [1, 0, 0, 0],
        [0, -1, 0, 0],
        [0, 0, -1, 0],
        [0, 0, 0, 1]
    ])

    transform_matrix_z_90 = np.array([
        [0, -1, 0, 0],
        [1,  0, 0, 0],
        [0,  0, 1, 0],
        [0,  0, 0, 1]
    ])

    # 添加一个额外的Z轴反转矩阵，用于确保Z轴朝下
    transform_matrix_z_down = np.array([
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, -1, 0],
        [0, 0, 0, 1]
    ])

    # 迭代查找并提取立方体
    while remaining_pointcloud_count > 50 and countdown > 0 and movecount < cube_num:
        # 从立方体网格模型中采样点
        cube_point_cloud = cube_mesh.sample_points_uniformly(number_of_points=50000) 
        cube_point_cloud = filter_point_cloud_by_depth(cube_point_cloud, depth_threshold=-0.01)

        # 将立方体与当前剩余的场景点云进行配准
        transform, remaining_pointcloud, deleted_pointcloud, fitness = register_and_filter(
            remaining_pointcloud, cube_point_cloud
        )

        remaining_pointcloud_count = len(remaining_pointcloud.points)

        # 如果匹配度超过最小阈值，则减少倒计时
        if fitness > 0.01:
            countdown -= 1

        print(f"迭代 {50 - countdown}: 匹配度 = {fitness:.4f}, 剩余点数: {remaining_pointcloud_count}")

        # 仅在匹配足够好时继续
        if fitness > 0.40:  # 略微降低阈值以检测更多立方体
            print(f"正在处理立方体 #{movecount+1}")

            # 对齐Z轴向下，同时保持XY方向
            aligned_transform = align_transform_z_axis_preserving_xy(transform)

            # 更新变换广播器（用于RViz等可视化）
            if 'broadcaster' in globals():
                broadcaster.update(aligned_transform)

            # 创建抓取变换
            grasp_transform = aligned_transform @ transform_matrix_x_180
            grasp_transform_rotate = aligned_transform @ transform_matrix_x_180 @ transform_matrix_z_90
            # 再次检查并确保最终的抓取变换Z轴朝下
            z_axis_grasp = grasp_transform[:3, 2]
            if z_axis_grasp[2] > 0:
                grasp_transform = grasp_transform @ transform_matrix_z_down
                print("已调整grasp_transform以确保Z轴朝下")
            
            z_axis_grasp_rotate = grasp_transform_rotate[:3, 2]
            if z_axis_grasp_rotate[2] > 0:
                grasp_transform_rotate = grasp_transform_rotate @ transform_matrix_z_down
                print("已调整grasp_transform_rotate以确保Z轴朝下")

            # 转换检测到的立方体点云（用于可视化或检查）
            cube_point_cloud_transformed = copy.deepcopy(deleted_pointcloud)
            cube_point_cloud_transformed = cube_point_cloud_transformed.transform(np.linalg.inv(grasp_transform))

            # 尝试生成检测到的立方体的顶部视图图像
            try:
                cube_point_cloud_transformed_cubes = enlarge_points_as_cubes(cube_point_cloud_transformed)
                cube_top_image = triangle_mesh_to_image(cube_point_cloud_transformed_cubes, image_size=(100, 100))
                cube_top_image = (cube_top_image / cube_top_image.max() * 255).astype(np.uint8)
                plt.imsave(f"cube_{movecount+1}_top_view.png", cube_top_image)
            except Exception as e:
                print(f"警告: 无法生成顶部视图图像: {e}")

            # 为碰撞检查生成抓取器网格
            grasp_mesh, gripper_meshes_rotate = generate_gripper_from_transform(grasp_transform)

            # 尝试两种抓取方向，并选择没有碰撞的一种
            grasp_final_matrix = None
            
            # 尝试标准抓取方向
            if not check_grasp_collision(grasp_mesh, original_point_cloud):
                grasp_final_matrix = grasp_transform
                print("使用标准抓取方向")
            # 尝试旋转90°的抓取方向
            elif not check_grasp_collision(gripper_meshes_rotate, original_point_cloud):
                grasp_final_matrix = grasp_transform_rotate
                print("使用旋转90°的抓取方向")
            else:
                print("两种抓取方向都发生碰撞，跳过此立方体")

            # 如果找到有效的抓取，则保存该变换矩阵
            if grasp_final_matrix is not None:
                countdown = 50  # 重置倒计时

                # 计算用于运动规划的RPY和位置
                pick_rpy, pick_pos = matrix_to_rpy_and_translation(grasp_final_matrix)
                approach_offset = [0, 0, 0.10]  # 立方体上方10cm处
                pick_pos_approach = [a + b for a, b in zip(pick_pos, approach_offset)]

                print(f"立方体 #{movecount+1} 抓取位置: {pick_pos}")
                print(f"接近位置: {pick_pos_approach}")
                print(f"RPY方向: {pick_rpy}")

                # 将变换矩阵添加到结果列表
                T.append(grasp_final_matrix)
                movecount += 1

                # 可选：显示抓取变换矩阵
                print("抓取变换矩阵:")
                print(grasp_final_matrix)

                # 可选：可视化抓取
                vis_geometries = grasp_mesh
                vis_geometries.append(create_coordinate_frame(0.1))
                aligned_coordinate_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.1)
                # aligned_coordinate_frame.transform(aligned_transform)
                aligned_coordinate_frame.transform(grasp_transform_rotate)
                vis_geometries.append(aligned_coordinate_frame)
                # vis_geometries.append(deleted_pointcloud)
                # vis_geometries.append(remaining_pointcloud)
                vis_geometries.append(original_point_cloud)

                # 调用Open3D的可视化函数，传入正确格式的列表
                o3d.visualization.draw_geometries(vis_geometries, window_name=f"grasp visualization #{movecount}")



    print(f"在 {50 - countdown} 次迭代中找到 {len(T)} 个立方体")

    # 打印最终的抓取变换矩阵
    for i, transform in enumerate(T):
        print(f"立方体 #{i+1} 变换:")
        print(transform)

    return T
           
Ts = pointcloud_process(filtered_point_cloud)
broadcaster.stop()


0.8179587526400796
0
[[ 4.38259844e-02 -9.99037767e-01 -1.67999712e-03  5.97930303e-01]
 [-9.98841455e-01 -4.38507035e-02  1.98208077e-02  3.69790012e-01]
 [-1.98754045e-02  8.09384358e-04 -9.99802137e-01  2.22112274e-02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[0.5979303030658479, 0.36979001166844633, 0.12221122735515641] [3.1407831092297234, 0.019876713333704332, -1.5269476334677399]
0.7434186132740082
0.7347262382240463
0.8167718273086129
1
[[ 0.03674522 -0.99932316  0.00173772  0.59801578]
 [-0.99908252 -0.03669799  0.02207643  0.1298582 ]
 [-0.02199771 -0.00254732 -0.99975478  0.02223913]
 [ 0.          0.          0.          1.        ]]
[0.5980157750702272, 0.12985820163686562, 0.1222391338536466] [-3.1390447095189127, 0.021999488251177812, -1.534033930286436]
0.7154297420616444
Correcting Z axis
0.8271129603179532
2
[[-0.04285631 -0.99891833  0.01804187  0.59952656]
 [-0.99907866  0.0428903   0.0015007   0.20850403]
 [-0.0022729  -0.01796093 -0.9998

In [14]:
Ts.__len__()

10

In [15]:
import numpy as np
import open3d as o3d
import copy

def generate_pascal_triangle_transforms(t, T):
    """
    Generate a list of transformation matrices for a Pascal triangle arrangement.
    Each cube's center position is used as the translation part of the transform matrix.
    """
    level = 1
    total = 1
    while total < t:
        level += 1
        total += level

    transforms = []
    cube_size = 0.045  # 4.5 cm
    spacing_xy = cube_size * 1.25  # Increase spacing to 1.25 times the cube size
    spacing_z = cube_size * 1.05   # Use the same spacing in the vertical direction

    current_pos = 0
    for row in range(level-1, -1, -1):
        for col in range(row + 1):
            if current_pos >= t:
                break

            center_x = 0
            center_y = (col - row/2) * spacing_xy
            center_z = (level - 1 - row) * spacing_z

            # Create local transformation matrix
            local_transform = np.eye(4)
            local_transform[:3, 3] = [center_x, center_y, center_z]

            # Combine local transformation with T transformation
            transform = np.dot(T, local_transform)
            transforms.append(transform)
            current_pos += 1

        if current_pos >= t:
            break

    return transforms

def create_coordinate_frame(size=0.1, transform=None):
    frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=size)
    if transform is not None:
        frame.transform(transform)
    return frame

def visualize_pascal_triangle(transforms, T):
    # Create a cube centered at the origin
    cube = o3d.geometry.TriangleMesh.create_box(
        width=0.045,
        height=0.045, 
        depth=0.045
    )
    # Move the cube to be centered at the origin
    cube.translate([-0.045/2, -0.045/2, -0.045/2])
    cube.compute_vertex_normals()

    vis = o3d.visualization.Visualizer()
    vis.create_window()

    # Add world coordinate frame
    world_frame = create_coordinate_frame(size=0.2)
    vis.add_geometry(world_frame)

    # Add T coordinate frame
    t_frame = create_coordinate_frame(size=0.2, transform=T)
    vis.add_geometry(t_frame)

    # Add all cubes and their local coordinate frames
    for transform in transforms:
        # Add cube
        cube_copy = copy.deepcopy(cube)
        cube_copy.transform(transform)
        vis.add_geometry(cube_copy)
        
        # Add local coordinate frame
        local_frame = create_coordinate_frame(size=0.05, transform=transform)
        vis.add_geometry(local_frame)

    opt = vis.get_render_option()
    opt.background_color = np.asarray([0.5, 0.5, 0.5])

    ctr = vis.get_view_control()
    ctr.set_zoom(0.2)  # Adjust zoom to fit larger spacing
    ctr.set_front([-0.8, -0.5, 0.5])
    ctr.set_lookat([0, 0, 0])
    ctr.set_up([0, 0, 1])

    vis.run()
    vis.destroy_window()


# 3. Motion Planning, movement, and grasp

In [16]:
from utils import generate_pascal_triangle_transforms
import numpy as np

In [17]:
t = Ts.__len__()
# t = 2
# 创建T矩阵（示例：绕Z轴旋转45度并平移）
T = np.eye(4)
theta = 0
T[:3, :3] = np.array([
    [np.cos(theta), -np.sin(theta), 0],
    [np.sin(theta), np.cos(theta), 0],
    [0, 0, 1]
])
T[:3, 3] = [0.3, 0.00, 0]

aim_transforms = generate_pascal_triangle_transforms(t, T)
visualize_pascal_triangle(aim_transforms, T)

[ WARN] [1742776370.217938829, 717.669000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 717.665000 according to authority unknown_publisher


In [18]:
aim_transforms

[ WARN] [1742776370.219714799, 717.671000000]: TF_REPEATED_DATA ignoring data with redundant timestamp for frame target_frame (parent world) at time 717.665000 according to authority /my_gripper_node_71928_1742776328347


[array([[ 1.      ,  0.      ,  0.      ,  0.3     ],
        [ 0.      ,  1.      ,  0.      , -0.084375],
        [ 0.      ,  0.      ,  1.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  1.      ]]),
 array([[ 1.      ,  0.      ,  0.      ,  0.3     ],
        [ 0.      ,  1.      ,  0.      , -0.028125],
        [ 0.      ,  0.      ,  1.      ,  0.      ],
        [ 0.      ,  0.      ,  0.      ,  1.      ]]),
 array([[1.      , 0.      , 0.      , 0.3     ],
        [0.      , 1.      , 0.      , 0.028125],
        [0.      , 0.      , 1.      , 0.      ],
        [0.      , 0.      , 0.      , 1.      ]]),
 array([[1.      , 0.      , 0.      , 0.3     ],
        [0.      , 1.      , 0.      , 0.084375],
        [0.      , 0.      , 1.      , 0.      ],
        [0.      , 0.      , 0.      , 1.      ]]),
 array([[ 1.     ,  0.     ,  0.     ,  0.3    ],
        [ 0.     ,  1.     ,  0.     , -0.05625],
        [ 0.     ,  0.     ,  1.     ,  0.04725],
        [ 

In [19]:
Ts

[array([[ 4.38259844e-02, -9.99037767e-01, -1.67999712e-03,
          5.97930303e-01],
        [-9.98841455e-01, -4.38507035e-02,  1.98208077e-02,
          3.69790012e-01],
        [-1.98754045e-02,  8.09384358e-04, -9.99802137e-01,
          2.22112274e-02],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00]]),
 array([[ 0.03674522, -0.99932316,  0.00173772,  0.59801578],
        [-0.99908252, -0.03669799,  0.02207643,  0.1298582 ],
        [-0.02199771, -0.00254732, -0.99975478,  0.02223913],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.04285631, -0.99891833,  0.01804187,  0.59952656],
        [-0.99907866,  0.0428903 ,  0.0015007 ,  0.20850403],
        [-0.0022729 , -0.01796093, -0.99983611,  0.02229985],
        [ 0.        ,  0.        ,  0.        ,  1.        ]]),
 array([[-0.03025034, -0.99943026,  0.01496937,  0.59946423],
        [-0.99953686,  0.03029646,  0.00286342,  0.28832629],
        [-0.00331531, -0.0

In [20]:
# demostrate the movement to the head of identified cubes
# for T in Ts:
#     pick_rpy, pick_pos = matrix_to_rpy_and_translation(T)
#     pick_pos_ = [a + b for a, b in zip(pick_pos, [0.04, 0.00, 0.10])]
#     pick_rpy = [a + b for a, b in zip(pick_rpy, [0, 0, 0])]
#     print(pick_rpy, pick_pos)
#     pick_place.move(pick_pos_, pick_rpy)
# Modified movement demonstration code
def demonstrate_movement_to_cubes(Ts, pick_place, offset=[0.00, 0.00, 0.10]):
    for i, T in enumerate(Ts):
        try:
            pick_rpy, pick_pos = matrix_to_rpy_and_translation(T)
            pick_pos_approach = [a + b for a, b in zip(pick_pos, offset)]
            
            try:
                pick_place.move(pick_pos_approach, pick_rpy)
                print(f"Successfully moved to approach position for cube #{i+1}")
            except ValueError as e:
                if "too many values to unpack" in str(e):
                    print(f"Note: Handled unpacking error in move operation for cube #{i+1}")
                else:
                    raise
        except Exception as e:
            print(f"Error processing cube #{i+1}: {e}")

# Use the modified function
demonstrate_movement_to_cubes(Ts, pick_place)


[INFO] [1742776370.244206, 717.691000]: Table added to the scene to prevent collision below z = 0.001
[INFO] [1742776370.245345, 717.692000]: Target position set to: [0.5979303030658479, 0.36979001166844633, 0.12221122735515641] and RPY: [3.1407831092297234, 0.019876713333704332, -1.5269476334677399]
[INFO] [1742776372.740891, 720.176000]: Table 'constraint_table' removed from the planning scene.
[INFO] [1742776372.743284, 720.179000]: Table 'constraint_table' removed from the planning scene.
[INFO] [1742776372.743932, 720.181000]: Move successful to position: [0.5979303030658479, 0.36979001166844633, 0.12221122735515641] and RPY: [3.1407831092297234, 0.019876713333704332, -1.5269476334677399]
Successfully moved to approach position for cube #1
[INFO] [1742776372.745722, 720.181000]: Table added to the scene to prevent collision below z = 0.001
[INFO] [1742776372.746302, 720.182000]: Target position set to: [0.5980157750702272, 0.12985820163686562, 0.1222391338536466] and RPY: [-3.1390

KeyboardInterrupt: 

In [ ]:
# move the minipulator to the aim position
for T in aim_transforms:
    transform_matrix_x_180 = np.array([
        [1, 0, 0, 0],
        [0, -1, 0, 0],
        [0, 0, -1, 0],
        [0, 0, 0, 1]
    ])
    transform_matrix_z_90 = np.array([
        [0, -1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])
    pick_rpy, pick_pos = matrix_to_rpy_and_translation(T@transform_matrix_x_180@transform_matrix_z_90)
    pick_pos_ = [a + b for a, b in zip(pick_pos, [0.0, 0, 0.13])]
    pick_rpy = [a + b for a, b in zip(pick_rpy, [0, 0, 0])]
    pick_place.move(pick_pos_, pick_rpy)


[INFO] [1742775882.787234, 233.940000]: Table added to the scene to prevent collision below z = 0.001
[INFO] [1742775882.788606, 233.942000]: Target position set to: [0.3, -0.08437499999999999, 0.13] and RPY: [3.141592653589793, 0.0, -1.5707963267948966]
[INFO] [1742775884.055832, 235.200000]: Table 'constraint_table' removed from the planning scene.
[INFO] [1742775884.058332, 235.208000]: Table 'constraint_table' removed from the planning scene.
[INFO] [1742775884.058954, 235.210000]: Move successful to position: [0.3, -0.08437499999999999, 0.13] and RPY: [3.141592653589793, 0.0, -1.5707963267948966]
[INFO] [1742775884.060978, 235.211000]: Table added to the scene to prevent collision below z = 0.001
[INFO] [1742775884.061651, 235.213000]: Target position set to: [0.3, -0.028124999999999997, 0.13] and RPY: [3.141592653589793, 0.0, -1.5707963267948966]
[INFO] [1742775884.623352, 235.770000]: Table 'constraint_table' removed from the planning scene.
[INFO] [1742775884.626009, 235.772000

In [22]:
# # pick and place the first cube 
# transform_matrix_x_180 = np.array([
#     [1, 0, 0, 0],
#     [0, -1, 0, 0],
#     [0, 0, -1, 0],
#     [0, 0, 0, 1]
# ])
# transform_matrix_z_90 = np.array([
#     [0, -1, 0, 0],
#     [1, 0, 0, 0],
#     [0, 0, 1, 0],
#     [0, 0, 0, 1]
# ])

# pick_rpy, pick_pos = matrix_to_rpy_and_translation(Ts[0])
# pick_pos_ = [a + b for a, b in zip(pick_pos, [0.00, 0, 0.00])]
# pick_rpy = [a + b for a, b in zip(pick_rpy, [0, 0, 0])]
    
# place_rpy, place_pos = matrix_to_rpy_and_translation(aim_transforms[0]@transform_matrix_x_180@transform_matrix_z_90)
# place_pos_ = [a + b for a, b in zip(place_pos, [0.0, 0, 0.04])]

# pick_place.pick_and_place(
#     pick_pos=pick_pos_,
#     pick_rpy=pick_rpy,
#     place_pos=place_pos_,
#     place_rpy=place_rpy
# )


In [21]:
# pick and place following cubes 
for i in range(0, Ts.__len__()):
    transform_matrix_x_180 = np.array([
    [1, 0, 0, 0],
    [0, -1, 0, 0],
    [0, 0, -1, 0],
    [0, 0, 0, 1]
    ])
    transform_matrix_z_90 = np.array([
        [0, -1, 0, 0],
        [1, 0, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ])

    pick_rpy, pick_pos = matrix_to_rpy_and_translation(Ts[i])
    pick_pos_ = [a + b for a, b in zip(pick_pos, [0.0, 0, 0.008])]
    pick_rpy = [a + b for a, b in zip(pick_rpy, [0, 0, 0])]

    place_rpy, place_pos = matrix_to_rpy_and_translation(aim_transforms[i]@transform_matrix_x_180@transform_matrix_z_90)
    place_pos_ = [a + b for a, b in zip(place_pos, [0.0, 0, 0.02])]

    pick_place.pick_and_place(
        pick_pos=pick_pos_,
        pick_rpy=pick_rpy,
        place_pos=place_pos_,
        place_rpy=place_rpy,
        extra_pick_patch = True
    )

NameError: name 'transform_matrix_x_180' is not defined